# Generated by Django 5.1.1 on 2024-09-17 00:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nro_legajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=50)),
                ('apellido_empleado', models.CharField(max_length=50)),
                ('sexo_empleado', models.CharField(max_length=1)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_nacimiento', models.DateField()),
                ('fecha_de_ingreso', models.DateField()),
                ('fecha_de_egreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('nacionalidad', models.IntegerField()),
                ('cod_obra_social', models.IntegerField(blank=True, null=True)),
                ('mod_contratacion', models.IntegerField(blank=True, null=True)),
                ('puesto', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('fecha_liquidacion', models.DateField(default=datetime.date.today)),
                ('total_horas_extras_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_horas_extras_100', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_dias_ausencia', models.IntegerField(default=0)),
                ('total_liquidacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LIQUIDADO', 'Liquidado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominas.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('HE', 'Horas Extras'), ('AS', 'Ausencia'), ('LI', 'Licencia'), ('OT', 'Otra')], max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('horas_extras_50', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horas_extras_100', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dias_ausencia', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominas.empleado')),
            ],
        ),
    ]
