# Generated by Django 5.1.1 on 2024-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cod_obra_social',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo_empleado',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
