# Generated by Django 5.1.1 on 2024-09-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0002_remove_empleado_cod_obra_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='mod_contratacion',
            field=models.CharField(blank=True, choices=[('T', 'Temporal'), ('P', 'Permanente')], max_length=1, null=True),
        ),
    ]
