# Generated by Django 5.1.1 on 2024-09-17 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0003_alter_empleado_mod_contratacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='horas_extras_100',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='horas_extras_50',
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 9, 16)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novedad',
            name='fecha',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.CharField(choices=[('AS', 'Ausencia'), ('LI', 'Licencia'), ('OT', 'Otra')], max_length=2),
        ),
    ]
