# Generated by Django 5.1.1 on 2024-09-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0005_remove_novedad_dias_ausencia_alter_novedad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.CharField(choices=[('AS', 'Ausencia'), ('LI', 'Licencia')], max_length=2),
        ),
    ]
