# Generated by Django 5.1.1 on 2024-09-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0006_alter_novedad_tipo_novedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='total_horas_extras_100',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='total_horas_extras_50',
        ),
    ]
