# Generated by Django 5.1.1 on 2024-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0008_alter_liquidacion_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
