# Generated by Django 5.1.1 on 2024-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0009_empleado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
