# Generated by Django 5.1.1 on 2024-09-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0010_alter_empleado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_de_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
