# Generated by Django 5.1.1 on 2024-09-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0011_alter_empleado_fecha_de_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_de_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_de_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
